# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basic.ui'
#
# Created: Wed Feb 12 15:22:43 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(435, 48)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 431, 45))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.updateToggle = QtGui.QSlider(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateToggle.sizePolicy().hasHeightForWidth())
        self.updateToggle.setSizePolicy(sizePolicy)
        self.updateToggle.setMaximumSize(QtCore.QSize(60, 16777215))
        self.updateToggle.setMaximum(1)
        self.updateToggle.setPageStep(1)
        self.updateToggle.setProperty("value", 1)
        self.updateToggle.setOrientation(QtCore.Qt.Horizontal)
        self.updateToggle.setObjectName("updateToggle")
        self.horizontalLayout_2.addWidget(self.updateToggle)
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.updateNow = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.updateNow.setEnabled(False)
        self.updateNow.setCheckable(False)
        self.updateNow.setObjectName("updateNow")
        self.horizontalLayout.addWidget(self.updateNow)
        self.restartNow = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.restartNow.setObjectName("restartNow")
        self.horizontalLayout.addWidget(self.restartNow)
        self.pauseGame = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pauseGame.setObjectName("pauseGame")
        self.horizontalLayout.addWidget(self.pauseGame)
        self.horizontalLayout.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_3.setBuddy(self.updateToggle)
        self.label_2.setBuddy(self.updateToggle)
        self.label.setBuddy(self.updateToggle)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Instapy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Update control", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Automatic", None, QtGui.QApplication.UnicodeUTF8))
        self.updateNow.setText(QtGui.QApplication.translate("MainWindow", "Update Now", None, QtGui.QApplication.UnicodeUTF8))
        self.restartNow.setText(QtGui.QApplication.translate("MainWindow", "Restart Now", None, QtGui.QApplication.UnicodeUTF8))
        self.pauseGame.setText(QtGui.QApplication.translate("MainWindow", "Toggle Execution", None, QtGui.QApplication.UnicodeUTF8))

